spring:
  application:
    name: RATING-SERVICE-MICRO

  config:
    import: optional:configserver:http://localhost:8083

  data:
    mongodb:
      url: mongodb://localhost:27017/microservices

server:
  port: 8089

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
